version: '2'
services:
  yikondi-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/yikondi/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yikondi
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
