export const enum LifeConstantName {
  HEIGHT = 'HEIGHT',
  WEIGHT = 'WEIGHT',
  BLOOD_GROUP = 'BLOOD_GROUP',
  BLOOD_SUGAR = 'BLOOD_SUGAR',
  ELECTROPHORESIS = 'ELECTROPHORESIS',
  CHRONIC_MYELOGENOUS_LEUKEMIA = 'CHRONIC_MYELOGENOUS_LEUKEMIA'
}
